- name: Setup gpg key
  apt_key:
    url: https://downloads.avax.network/qmallgo.gpg.key
    state: present

- name: Setup qmallgo repo
  apt_repository:
    repo: deb https://downloads.avax.network/apt bionic main
    state: present

- name: Setup golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports 
    state: present

- name: Install go
  apt:
    name: golang
    state: latest

- name: Update git clone
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_folder }}"
    version: "{{ tag }}"
    update: yes
    force: yes

- name: Setup systemd
  template:
    src: templates/qmallgo.service.j2
    dest: /etc/systemd/system/qmallgo.service
    mode: 0755

- name: Create avalanche user
  user:
    name: "{{ ava_user }}"
    shell: /bin/bash
    uid: 114
    group: "{{ ava_group }}"

- name: Create avalanche config dir
  file:
    path: /etc/qmallgo
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create avalanche C config dir
  file:
    path: /etc/qmallgo/C
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create avalanche log dir
  file:
    path: "{{ log_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create avalanche database dir
  file:
    path: "{{ db_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory

- name: Create avalanche plugins directory
  file:
    path: "{{ plugin_dir }}"
    owner: "{{ ava_user }}"
    group: "{{ ava_group }}"
    state: directory
    recurse: yes

- name: Build qmallgo
  command: ./scripts/build.sh
  args:
    chdir: "{{ repo_folder }}"

- name: Copy qmallgo binaries to the correct location
  command: cp build/qmallgo /usr/local/bin/qmallgo
  args:
    chdir: "{{ repo_folder }}"

- name: Copy evm binaries to the correct location
  command: cp build/plugins/evm {{ plugin_dir }}
  args:
    chdir: "{{ repo_folder }}"


- name: Configure avalanche 
  template:
    src: templates/conf.json.j2
    dest: /etc/qmallgo/conf.json
    mode: 0644

- name: Configure avalanche C Chain
  template:
    src: templates/C/config.json.j2
    dest: /etc/qmallgo/C/config.json
    mode: 0644

- name: Enable Avalanche
  systemd:
    name: qmallgo
    enabled: yes
