---
ava_user: avalanche
ava_group: admin
network: mainnet
db_dir: /data/qmallgo
log_dir: /var/log/qmallgo
config_dir: /etc/qmallgo
plugin_dir: /usr/local/lib/qmallgo/plugins
repo_url: https://github.com/dim4egster/qmallgo
repo_folder: /tmp/qmallgo
